; ModuleID = 'inputs-complex/url_parser.h/gen_char_category_table.i.bc'
source_filename = "inputs-complex/url_parser.h/gen_char_category_table.i"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.__sFILE = type { i8*, i32, i32, i16, i16, %struct.__sbuf, i32, i8*, i32 (i8*)*, i32 (i8*, i8*, i32)*, i64 (i8*, i64, i32)*, i32 (i8*, i8*, i32)*, %struct.__sbuf, %struct.__sFILEX*, i32, [3 x i8], [1 x i8], %struct.__sbuf, i32, i64 }
%struct.__sFILEX = type opaque
%struct.__sbuf = type { i8*, i32 }

@.str = private unnamed_addr constant [63 x i8] c"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\00", align 1
@alnum = dso_local constant i8* getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), align 8
@.str.1 = private unnamed_addr constant [5 x i8] c"-._~\00", align 1
@unreserved = dso_local constant i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), align 8
@.str.2 = private unnamed_addr constant [12 x i8] c"!$&'()*+,;=\00", align 1
@subdelim = dso_local constant i8* getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0), align 8
@char_cat = dso_local global [256 x i32] zeroinitializer, align 16
@.str.3 = private unnamed_addr constant [233 x i8] c"// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\0A\0A const unsigned short char_cat[256] = {\0A//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F\0A\00", align 1
@.str.4 = private unnamed_addr constant [10 x i8] c" 0x%03x%c\00", align 1
@.str.5 = private unnamed_addr constant [21 x i8] c" // %01X0 ... %01XF\0A\00", align 1
@.str.6 = private unnamed_addr constant [5 x i8] c"};\0A\0A\00", align 1
@.str.7 = private unnamed_addr constant [4 x i8] c"+-.\00", align 1
@.str.8 = private unnamed_addr constant [8 x i8] c":/?#[]@\00", align 1
@.str.9 = private unnamed_addr constant [5 x i8] c":@/%\00", align 1
@.str.10 = private unnamed_addr constant [11 x i8] c"0123456789\00", align 1
@.str.11 = private unnamed_addr constant [13 x i8] c"abcdefABCDEF\00", align 1
@.str.12 = private unnamed_addr constant [6 x i8] c"/?:@%\00", align 1
@.str.13 = private unnamed_addr constant [3 x i8] c":%\00", align 1
@.str.14 = private unnamed_addr constant [14 x i8] c"abcdefABCDEF:\00", align 1

; Function Attrs: alwaysinline nounwind uwtable
define dso_local i32 @__sputc(i32 noundef %0, %struct.__sFILE* noundef %1) #0 {
  %3 = alloca i32, align 4
  %4 = alloca i32, align 4
  %5 = alloca %struct.__sFILE*, align 8
  store i32 %0, i32* %4, align 4
  store %struct.__sFILE* %1, %struct.__sFILE** %5, align 8
  %6 = load %struct.__sFILE*, %struct.__sFILE** %5, align 8
  %7 = getelementptr inbounds %struct.__sFILE, %struct.__sFILE* %6, i32 0, i32 2
  %8 = load i32, i32* %7, align 4
  %9 = add nsw i32 %8, -1
  store i32 %9, i32* %7, align 4
  %10 = icmp sge i32 %9, 0
  br i1 %10, label %24, label %11

11:                                               ; preds = %2
  %12 = load %struct.__sFILE*, %struct.__sFILE** %5, align 8
  %13 = getelementptr inbounds %struct.__sFILE, %struct.__sFILE* %12, i32 0, i32 2
  %14 = load i32, i32* %13, align 4
  %15 = load %struct.__sFILE*, %struct.__sFILE** %5, align 8
  %16 = getelementptr inbounds %struct.__sFILE, %struct.__sFILE* %15, i32 0, i32 6
  %17 = load i32, i32* %16, align 8
  %18 = icmp sge i32 %14, %17
  br i1 %18, label %19, label %32

19:                                               ; preds = %11
  %20 = load i32, i32* %4, align 4
  %21 = trunc i32 %20 to i8
  %22 = sext i8 %21 to i32
  %23 = icmp ne i32 %22, 10
  br i1 %23, label %24, label %32

24:                                               ; preds = %19, %2
  %25 = load i32, i32* %4, align 4
  %26 = trunc i32 %25 to i8
  %27 = load %struct.__sFILE*, %struct.__sFILE** %5, align 8
  %28 = getelementptr inbounds %struct.__sFILE, %struct.__sFILE* %27, i32 0, i32 0
  %29 = load i8*, i8** %28, align 8
  %30 = getelementptr inbounds i8, i8* %29, i32 1
  store i8* %30, i8** %28, align 8
  store i8 %26, i8* %29, align 1
  %31 = zext i8 %26 to i32
  store i32 %31, i32* %3, align 4
  br label %36

32:                                               ; preds = %19, %11
  %33 = load i32, i32* %4, align 4
  %34 = load %struct.__sFILE*, %struct.__sFILE** %5, align 8
  %35 = call i32 @__swbuf(i32 noundef %33, %struct.__sFILE* noundef %34)
  store i32 %35, i32* %3, align 4
  br label %36

36:                                               ; preds = %32, %24
  %37 = load i32, i32* %3, align 4
  ret i32 %37
}

declare dso_local i32 @__swbuf(i32 noundef, %struct.__sFILE* noundef) #1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @fill(i32 noundef %0, i8* noundef %1, i8* noundef %2) #2 {
  %4 = alloca i32, align 4
  %5 = alloca i8*, align 8
  %6 = alloca i8*, align 8
  store i32 %0, i32* %4, align 4
  store i8* %1, i8** %5, align 8
  store i8* %2, i8** %6, align 8
  br label %7

7:                                                ; preds = %19, %3
  %8 = load i8*, i8** %5, align 8
  %9 = load i8, i8* %8, align 1
  %10 = icmp ne i8 %9, 0
  br i1 %10, label %11, label %22

11:                                               ; preds = %7
  %12 = load i32, i32* %4, align 4
  %13 = load i8*, i8** %5, align 8
  %14 = load i8, i8* %13, align 1
  %15 = zext i8 %14 to i64
  %16 = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %15
  %17 = load i32, i32* %16, align 4
  %18 = or i32 %17, %12
  store i32 %18, i32* %16, align 4
  br label %19

19:                                               ; preds = %11
  %20 = load i8*, i8** %5, align 8
  %21 = getelementptr inbounds i8, i8* %20, i32 1
  store i8* %21, i8** %5, align 8
  br label %7, !llvm.loop !4

22:                                               ; preds = %7
  br label %23

23:                                               ; preds = %35, %22
  %24 = load i8*, i8** %6, align 8
  %25 = load i8, i8* %24, align 1
  %26 = icmp ne i8 %25, 0
  br i1 %26, label %27, label %38

27:                                               ; preds = %23
  %28 = load i32, i32* %4, align 4
  %29 = load i8*, i8** %6, align 8
  %30 = load i8, i8* %29, align 1
  %31 = zext i8 %30 to i64
  %32 = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %31
  %33 = load i32, i32* %32, align 4
  %34 = or i32 %33, %28
  store i32 %34, i32* %32, align 4
  br label %35

35:                                               ; preds = %27
  %36 = load i8*, i8** %6, align 8
  %37 = getelementptr inbounds i8, i8* %36, i32 1
  store i8* %37, i8** %6, align 8
  br label %23, !llvm.loop !6

38:                                               ; preds = %23
  ret void
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local void @print_table() #2 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  %3 = alloca i32, align 4
  %4 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([233 x i8], [233 x i8]* @.str.3, i64 0, i64 0))
  store i32 0, i32* %1, align 4
  br label %5

5:                                                ; preds = %34, %0
  %6 = load i32, i32* %1, align 4
  %7 = icmp ult i32 %6, 16
  br i1 %7, label %8, label %37

8:                                                ; preds = %5
  %9 = call i32 @putchar(i32 noundef 32)
  store i32 0, i32* %2, align 4
  br label %10

10:                                               ; preds = %27, %8
  %11 = load i32, i32* %2, align 4
  %12 = icmp ult i32 %11, 16
  br i1 %12, label %13, label %30

13:                                               ; preds = %10
  %14 = load i32, i32* %1, align 4
  %15 = mul i32 %14, 16
  %16 = load i32, i32* %2, align 4
  %17 = add i32 %15, %16
  store i32 %17, i32* %3, align 4
  %18 = load i32, i32* %3, align 4
  %19 = zext i32 %18 to i64
  %20 = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %19
  %21 = load i32, i32* %20, align 4
  %22 = load i32, i32* %3, align 4
  %23 = icmp eq i32 %22, 255
  %24 = zext i1 %23 to i64
  %25 = select i1 %23, i32 32, i32 44
  %26 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([10 x i8], [10 x i8]* @.str.4, i64 0, i64 0), i32 noundef %21, i32 noundef %25)
  br label %27

27:                                               ; preds = %13
  %28 = load i32, i32* %2, align 4
  %29 = add i32 %28, 1
  store i32 %29, i32* %2, align 4
  br label %10, !llvm.loop !7

30:                                               ; preds = %10
  %31 = load i32, i32* %1, align 4
  %32 = load i32, i32* %1, align 4
  %33 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([21 x i8], [21 x i8]* @.str.5, i64 0, i64 0), i32 noundef %31, i32 noundef %32)
  br label %34

34:                                               ; preds = %30
  %35 = load i32, i32* %1, align 4
  %36 = add i32 %35, 1
  store i32 %36, i32* %1, align 4
  br label %5, !llvm.loop !8

37:                                               ; preds = %5
  %38 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.6, i64 0, i64 0))
  ret void
}

declare dso_local i32 @printf(i8* noundef, ...) #1

declare dso_local i32 @putchar(i32 noundef) #1

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @main() #2 {
  call void @fill(i32 noundef 1, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([4 x i8], [4 x i8]* @.str.7, i64 0, i64 0))
  call void @fill(i32 noundef 2, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0))
  call void @fill(i32 noundef 4, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([8 x i8], [8 x i8]* @.str.8, i64 0, i64 0))
  call void @fill(i32 noundef 8, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0))
  call void @fill(i32 noundef 16, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.9, i64 0, i64 0))
  call void @fill(i32 noundef 16, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0))
  call void @fill(i32 noundef 32, i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @.str.10, i64 0, i64 0), i8* noundef getelementptr inbounds ([13 x i8], [13 x i8]* @.str.11, i64 0, i64 0))
  call void @fill(i32 noundef 64, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([6 x i8], [6 x i8]* @.str.12, i64 0, i64 0))
  call void @fill(i32 noundef 64, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0))
  call void @fill(i32 noundef 128, i8* noundef getelementptr inbounds ([63 x i8], [63 x i8]* @.str, i32 0, i32 0), i8* noundef getelementptr inbounds ([3 x i8], [3 x i8]* @.str.13, i64 0, i64 0))
  call void @fill(i32 noundef 128, i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.1, i32 0, i32 0), i8* noundef getelementptr inbounds ([12 x i8], [12 x i8]* @.str.2, i32 0, i32 0))
  call void @fill(i32 noundef 256, i8* noundef getelementptr inbounds ([11 x i8], [11 x i8]* @.str.10, i64 0, i64 0), i8* noundef getelementptr inbounds ([14 x i8], [14 x i8]* @.str.14, i64 0, i64 0))
  call void @print_table()
  ret i32 0
}

attributes #0 = { alwaysinline nounwind uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { noinline nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{i32 7, !"frame-pointer", i32 2}
!3 = !{!"clang version 14.0.0"}
!4 = distinct !{!4, !5}
!5 = !{!"llvm.loop.mustprogress"}
!6 = distinct !{!6, !5}
!7 = distinct !{!7, !5}
!8 = distinct !{!8, !5}
