use std::fmt::Write; // Import the Write trait for using write! macro
use std::io::{self, Write as IoWrite};

const CHAR_CAT: [u16; 256] = [0; 256]; // Placeholder for the char_cat array

fn print_table(output: &mut dyn IoWrite) -> io::Result<()> {
    writeln!(output, "// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!")?;
    writeln!(output, "\nstatic const unsigned short char_cat[256] = {{")?;
    writeln!(output, "//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F")?;

    for y in 0..16 {
        write!(output, " ")?;
        for x in 0..16 {
            let offset = y * 16 + x;
            write!(output, " 0x{:03x}{}", CHAR_CAT[offset as usize], if offset == 255 { ' ' } else { ',' })?;
        }
        writeln!(output, " // {:01X}0 ... {:01X}F", y, y)?;
    }
    writeln!(output, "}};\n")?;

    Ok(())
}

fn main() {
    let mut output = io::stdout(); // You can change this to any other writer
    if let Err(e) = print_table(&mut output) {
        eprintln!("Error writing to output: {}", e);
    }
}
