; ModuleID = 'inputs-complex/url.h/individual-funcs_gpt-4o_2025-01-16_21-12-16/print_table.i.bc'
source_filename = "inputs-complex/url.h/individual-funcs_gpt-4o_2025-01-16_21-12-16/print_table.i"
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx14.0.0"

@.str = private unnamed_addr constant [239 x i8] c"// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\0A\0Astatic const unsigned short char_cat[256] = {\0A//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F\0A\00", align 1
@.str.1 = private unnamed_addr constant [10 x i8] c" 0x%03x%c\00", align 1
@char_cat = global [256 x i32] zeroinitializer, align 4
@.str.2 = private unnamed_addr constant [21 x i8] c" // %01X0 ... %01XF\0A\00", align 1
@.str.3 = private unnamed_addr constant [5 x i8] c"};\0A\0A\00", align 1

; Function Attrs: noinline nounwind optnone ssp uwtable
define void @print_table() #0 {
entry:
  %y = alloca i32, align 4
  %x = alloca i32, align 4
  %offset = alloca i32, align 4
  %call = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([239 x i8], [239 x i8]* @.str, i64 0, i64 0))
  store i32 0, i32* %y, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc8, %entry
  %0 = load i32, i32* %y, align 4
  %cmp = icmp ult i32 %0, 16
  br i1 %cmp, label %for.body, label %for.end10

for.body:                                         ; preds = %for.cond
  %call1 = call i32 @putchar(i32 noundef 32)
  store i32 0, i32* %x, align 4
  br label %for.cond2

for.cond2:                                        ; preds = %for.inc, %for.body
  %1 = load i32, i32* %x, align 4
  %cmp3 = icmp ult i32 %1, 16
  br i1 %cmp3, label %for.body4, label %for.end

for.body4:                                        ; preds = %for.cond2
  %2 = load i32, i32* %y, align 4
  %mul = mul i32 %2, 16
  %3 = load i32, i32* %x, align 4
  %add = add i32 %mul, %3
  store i32 %add, i32* %offset, align 4
  %4 = load i32, i32* %offset, align 4
  %idxprom = zext i32 %4 to i64
  %arrayidx = getelementptr inbounds [256 x i32], [256 x i32]* @char_cat, i64 0, i64 %idxprom
  %5 = load i32, i32* %arrayidx, align 4
  %6 = load i32, i32* %offset, align 4
  %cmp5 = icmp eq i32 %6, 255
  %7 = zext i1 %cmp5 to i64
  %cond = select i1 %cmp5, i32 32, i32 44
  %call6 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([10 x i8], [10 x i8]* @.str.1, i64 0, i64 0), i32 noundef %5, i32 noundef %cond)
  br label %for.inc

for.inc:                                          ; preds = %for.body4
  %8 = load i32, i32* %x, align 4
  %inc = add i32 %8, 1
  store i32 %inc, i32* %x, align 4
  br label %for.cond2, !llvm.loop !10

for.end:                                          ; preds = %for.cond2
  %9 = load i32, i32* %y, align 4
  %10 = load i32, i32* %y, align 4
  %call7 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([21 x i8], [21 x i8]* @.str.2, i64 0, i64 0), i32 noundef %9, i32 noundef %10)
  br label %for.inc8

for.inc8:                                         ; preds = %for.end
  %11 = load i32, i32* %y, align 4
  %inc9 = add i32 %11, 1
  store i32 %inc9, i32* %y, align 4
  br label %for.cond, !llvm.loop !12

for.end10:                                        ; preds = %for.cond
  %call11 = call i32 (i8*, ...) @printf(i8* noundef getelementptr inbounds ([5 x i8], [5 x i8]* @.str.3, i64 0, i64 0))
  ret void
}

declare i32 @printf(i8* noundef, ...) #1

declare i32 @putchar(i32 noundef) #1

attributes #0 = { noinline nounwind optnone ssp uwtable "frame-pointer"="non-leaf" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="apple-m1" "target-features"="+aes,+crc,+crypto,+dotprod,+fp-armv8,+fp16fml,+fullfp16,+lse,+neon,+ras,+rcpc,+rdm,+sha2,+v8.5a,+zcm,+zcz" }
attributes #1 = { "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="apple-m1" "target-features"="+aes,+crc,+crypto,+dotprod,+fp-armv8,+fp16fml,+fullfp16,+lse,+neon,+ras,+rcpc,+rdm,+sha2,+v8.5a,+zcm,+zcz" }

!llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6, !7, !8}
!llvm.ident = !{!9}

!0 = !{i32 2, !"SDK Version", [2 x i32] [i32 14, i32 4]}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 1, !"branch-target-enforcement", i32 0}
!3 = !{i32 1, !"sign-return-address", i32 0}
!4 = !{i32 1, !"sign-return-address-all", i32 0}
!5 = !{i32 1, !"sign-return-address-with-bkey", i32 0}
!6 = !{i32 7, !"PIC Level", i32 2}
!7 = !{i32 7, !"uwtable", i32 1}
!8 = !{i32 7, !"frame-pointer", i32 1}
!9 = !{!"clang version 14.0.0 (git@github.com:davsec-lab/typedefextractor.git dfb083149f45185bece93228f47a1ca85d4c12a0)"}
!10 = distinct !{!10, !11}
!11 = !{!"llvm.loop.mustprogress"}
!12 = distinct !{!12, !11}
