struct __sbuf {
 unsigned char *_base;
 int _size;
};
struct __sFILEX;
int printf(const char * restrict, ...) __attribute__((__format__ (__printf__, 1, 2)));
int putchar(int);
enum Category
{
  Scheme = 0x01,
  Unreserved = 0x02,
  GenDelim = 0x04,
  SubDelim = 0x08,
  PCharSlash = 0x10,
  HexDigit = 0x20,
  Query = 0x40,
  Fragment = 0x40,
  Userinfo = 0x80,
  IPv6Char = 0x100,
};
unsigned char_cat[256];
void print_table()
{
 printf(
  "// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n"
  "\n"
  "static const unsigned short char_cat[256] = {\n"
  "//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F\n");
 for(unsigned y=0; y<16; ++y)
 {
  putchar(' ');
  for(unsigned x=0; x<16; ++x)
  {
   const unsigned offset = y*16+x;
   printf(" 0x%03x%c", char_cat[offset], (offset==255 ? ' ' : ',') );
  }
  printf(" // %01X0 ... %01XF\n", y, y);
 }
 printf("};\n\n");
}
