#![allow(unaligned_references)]
#[repr(u16)]
enum Category {
    Scheme = 0x01,
    Unreserved = 0x02,
    GenDelim = 0x04,
    SubDelim = 0x08,
    PCharSlash = 0x10,
    HexDigit = 0x20,
    Query = 0x40,
    Fragment = 0x41, // Changed to a unique value
    Userinfo = 0x80,
    IPv6Char = 0x100,
}

static CHAR_CAT: [u16; 256] = [0; 256]; // Initialize with default values

#[no_mangle]
#[no_mangle]
fn print_table() {
    println!(
        "// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n\
        \n\
        static const unsigned short char_cat[256] = {{\n\
        //   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F"
    );

    for y in 0..16 {
        print!(" ");
        for x in 0..16 {
            let offset = y * 16 + x;
            print!(
                " 0x{:03x}{}",
                CHAR_CAT[offset],
                if offset == 255 { ' ' } else { ',' }
            );
        }
        println!(" // {:01X}0 ... {:01X}F", y, y);
    }
    println!("}};\n");
}

#[no_mangle]
#[no_mangle]
fn main() {
    print_table();
}
